const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
test('WhatsApp fornece link individual; nao conduz agendamento; webhook autenticado e idempotente',async t=>{
 const env=require('./helpers/postgres').testEnvironment();
 process.env.EVOLUTION_WEBHOOK_SECRET='test-only-secret';process.env.PUBLIC_APP_URL='https://studiofy.example.test';
 const db=require('../database');await db.ready;
 t.after(async()=>{await db.close();await env.cleanup();});
 const webhook=require('../evolutionWebhook'),headers={'x-webhook-secret':'test-only-secret'},sent=[];
 const send=async(instance,phone,text)=>sent.push({instance,phone,text});
 const payload=(text,instance='test-a',id=crypto.randomUUID())=>({event:'messages.upsert',instance,data:{key:{remoteJid:'5511999990001@s.whatsapp.net',fromMe:false,id},message:{conversation:text}}});
 for(const [id,instance,name] of [[1,'test-a','Studio Bella'],[2,'test-b','Espaco Ana']])await db.runAsync("INSERT INTO assinaturas (id,barbearia_nome,responsavel_nome,telefone,metodo_pagamento,dia_vencimento,suporte_numero,whatsapp_session,status) VALUES ($1,$2,'Dono','5511999990000','mercado_pago',5,'',$3,'ativo')",[id,name,instance]);
 await assert.rejects(webhook.processarWebhookEvolution(payload('oi'),{}, {send}),e=>e.statusCode===401);
 const own=payload('oi');own.data.key.fromMe=true;assert.equal(webhook.extract(own),null);
 for(const jid of ['123@g.us','status@broadcast','123456789012@lid']){const p=payload('oi');p.data.key.remoteJid=jid;assert.equal(webhook.extract(p),null);}
 const p=payload('oi');await Promise.all([webhook.processarWebhookEvolution(p,headers,{send}),webhook.processarWebhookEvolution(p,headers,{send})]);
 assert.equal(sent.length,1);assert.match(sent[0].text,/Studio Bella/);assert.match(sent[0].text,/agendar\/studio-1/);
 await webhook.processarWebhookEvolution(payload('oi','test-b'),headers,{send});assert.match(sent[1].text,/Espaco Ana/);assert.match(sent[1].text,/agendar\/studio-2/);
 for(const text of ['1','Quero conversar com a Ana','14:00'])await webhook.processarWebhookEvolution(payload(text),headers,{send});
 assert.equal(sent.length,2);assert.equal((await db.getAsync('SELECT COUNT(*) AS n FROM agendamentos')).n,0);
 delete require.cache[require.resolve('../evolutionWebhook')];assert.equal((await require('../evolutionWebhook').processarWebhookEvolution(p,headers,{send})).duplicate,true);
 assert.equal(sent.length,2);
 const pending=payload('Ola');await webhook.processarWebhookEvolution(pending,headers,{send:async()=>{throw Error('offline');}});
 const row=await db.getAsync('SELECT * FROM whatsapp_messages WHERE message_id=$1',[pending.data.key.id]);assert.equal(row.status,'pending');
 await db.runAsync('UPDATE whatsapp_messages SET lease_until=0 WHERE id=$1',[row.id]);await webhook.drain(send);assert.equal(sent.length,3);
 await t.test('trial governa respostas e fila sem alterar mensagem ou backoff de transporte',async()=>{
  const started=new Date(),ends=new Date(started.getTime()+168*3600000);
  await db.runAsync("UPDATE assinaturas SET status='pendente',trial_status='active',trial_started_at=$1,trial_ends_at=$2 WHERE id=1",[started.toISOString(),ends]);
  await webhook.processarWebhookEvolution(payload('oi'),headers,{send});assert.equal(sent.length,4);
  const queued=payload('oi');
  const attemptStart=Date.now();
  await webhook.processarWebhookEvolution(queued,headers,{send:async()=>{throw Object.assign(Error('provider 429'),{statusCode:429});}});
  const pending=await db.getAsync('SELECT * FROM whatsapp_messages WHERE message_id=$1',[queued.data.key.id]);
  assert.equal(pending.attempts,1);
  assert.ok(pending.lease_until>=attemptStart+10000 && pending.lease_until<=Date.now()+10000);
  await db.runAsync("UPDATE assinaturas SET trial_started_at='2000-01-01T00:00:00.000Z',trial_ends_at='2000-01-08T00:00:00.000Z' WHERE id=1");
  const ignored=payload('oi');assert.equal((await webhook.processarWebhookEvolution(ignored,headers,{send})).reason,'payment_required');
  assert.equal(await db.getAsync('SELECT id FROM whatsapp_messages WHERE message_id=$1',[ignored.data.key.id]),undefined);
  await db.runAsync('UPDATE whatsapp_messages SET lease_until=0 WHERE id=$1',[pending.id]);
  const deferStart=Date.now();await webhook.drain(send);
  const deferred=await db.getAsync('SELECT * FROM whatsapp_messages WHERE id=$1',[pending.id]);
  assert.equal(sent.length,4);assert.equal(deferred.attempts,1);
  assert.equal(deferred.status,'pending');assert.equal(deferred.response,pending.response);
  assert.ok(deferred.lease_until>=deferStart+300000);
  await db.runAsync("UPDATE assinaturas SET status='ativo',payment_id='approved-test',ultimo_pagamento='2026-09-24',proximo_vencimento='2099-01-01' WHERE id=1");
  await db.runAsync('UPDATE whatsapp_messages SET lease_until=0 WHERE id=$1',[pending.id]);await webhook.drain(send);
  assert.equal(sent.length,5);assert.equal(sent[4].text,pending.response);
  assert.equal((await db.getAsync('SELECT status FROM whatsapp_messages WHERE id=$1',[pending.id])).status,'sent');
 });
});
