const {test}=require('node:test');
const assert=require('node:assert/strict');
const express=require('express');
test('Studiofy: fluxo completo, isolamento, concorrência e lembretes persistentes',async t=>{
 const env=require('./helpers/postgres').testEnvironment();
 process.env.LEGACY_ADMIN_EMAIL='studiofy-admin@example.test';process.env.LEGACY_ADMIN_PASSWORD='test-password';
 process.env.MERCADO_PAGO_ACCESS_TOKEN='';process.env.EVOLUTION_API_URL='';process.env.EVOLUTION_API_KEY='';
 const db=require('../database');await db.ready;
 const {createStudio}=require('../services/studiofy');
 const app=express();app.use(express.json({limit:'6mb'}));app.use('/api',require('../routes'));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();await env.cleanup();});
 const request=async(path,method='GET',body,token)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method,headers:{'Content-Type':'application/json',...(token?{'x-barbeiro-token':token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};};
 const tenants=[];
 for(let i=0;i<2;i++){
  const r=await request('/publico/assinaturas','POST',{barbeariaNome:'Studio '+i,responsavelNome:'Pessoa '+i,telefone:'551199999888'+i,email:`studio${i}@example.test`,senha:'test-password',metodoPagamento:'mercado_pago',diaVencimento:5,servicos:[{nome:'Manicure '+i,preco:30}]});assert.equal(r.status,201,JSON.stringify(r.body));
  const id=r.body.assinatura.id;
  await db.runAsync("UPDATE assinaturas SET status='ativo',status_assinatura='ATIVA',bloqueado=0,proximo_vencimento='2099-12-01',data_vencimento='2099-12-01',whatsapp_session=$1 WHERE id=$2",['test-instance-'+i,id]);
  const login=await request('/barbeiro/login','POST',{identificador:`studio${i}@example.test`,senha:'test-password'});assert.equal(login.status,200);
  const token=login.body.token;
  const panel=await request('/studiofy/painel','GET',null,token);assert.equal(panel.status,200,JSON.stringify(panel.body));tenants.push({id,token,panel:panel.body});
 }
 const [a,b]=tenants;
 let service,professional,booking;
 const future=new Date(Date.now()+86400000*2).toISOString().slice(0,10);
 const hours=Array.from({length:7},()=>[['08:00','18:00']]);
 await t.test('autenticação e serviços exclusivos por conta',async()=>{
  assert.equal((await request('/studiofy/painel')).status,401);
  assert.equal((await request('/studiofy/painel','GET',null,'forged')).status,401);
  const input={nome:'Alongamento',descricao:'Livre',preco:90,duracao:60,ativo:true};
  const r=await request('/studiofy/servicos','POST',input,a.token);assert.equal(r.status,201);service=r.body.id;
  assert.equal((await request('/studiofy/servicos/'+service,'PUT',{...input,preco:95},b.token)).status,404);
  assert.equal((await request('/studiofy/servicos/'+service,'PUT',{...input,preco:95},a.token)).status,200);
  assert.equal((await request('/studiofy/servicos','POST',{...input,duracao:-1},a.token)).status,400);
  assert.equal((await request('/studiofy/servicos','POST',{...input,preco:-1},a.token)).status,400);
  assert.equal((await request('/studiofy/servicos/'+service,'DELETE',null,b.token)).status,404);
  const panel=(await request('/studiofy/painel','GET',null,a.token)).body;professional=panel.profissionais[0].id;
  assert.ok(!b.panel.servicos.some(s=>s.id===service));
  assert.equal((await request('/studiofy/profissionais','POST',{nome:'Outro',ativo:true,servicos:[service]},b.token)).status,400);
 });
 await t.test('página pública, imagens, disponibilidade e isolamento',async()=>{
  const sharp=require('sharp');const png=await sharp({create:{width:16,height:16,channels:3,background:'blue'}}).png().toBuffer();
  const page={nome:'Studio Bella',descricao:'Beleza e cuidado',telefone:'11999998888',slug:'studio-bella',cor:'#2878ff',capa:'data:image/png;base64,'+png.toString('base64'),logo:null};
  assert.equal((await request('/studiofy/pagina','PUT',{...page,capa:'data:image/svg+xml;base64,PHN2Zz4='},a.token)).status,400);
  assert.equal((await request('/studiofy/pagina','PUT',{...page,capa:'data:image/png;base64,aGVsbG8='},a.token)).status,400);
  assert.equal((await request('/studiofy/pagina','PUT',page,a.token)).status,200);
  assert.equal((await request('/studiofy/pagina','PUT',page,b.token)).status,409);
  const publicPage=await request('/studiofy/public/studio-bella');assert.equal(publicPage.status,200);assert.equal(publicPage.body.nome,'Studio Bella');assert.match(publicPage.body.capa,/^data:image\/webp/);assert.equal(publicPage.body.senha_hash,undefined);
  assert.ok(publicPage.body.servicos.some(s=>s.id===service));assert.ok(!publicPage.body.servicos.some(s=>s.assinatura_id===b.id));
  assert.equal((await request('/studiofy/horarios','PUT',{horarios:hours},a.token)).status,200);
  assert.equal((await request('/studiofy/horarios','PUT',{horarios:[[['18:00','08:00']]]},a.token)).status,400);
 });
 const body=()=>({nome_cliente:'Gabriel',telefone:'11999990000',servico_id:service,profissional_id:professional,data:future,hora:'10:00'});
 await t.test('duas reservas simultâneas; conflito parcial de duração e profissional',async()=>{
  const results=await Promise.all([request('/studiofy/public/studio-bella/agendamentos','POST',body()),request('/studiofy/public/studio-bella/agendamentos','POST',body())]);
  assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);booking=results.find(r=>r.status===201).body.id;
  assert.equal((await request('/studiofy/public/studio-bella/agendamentos','POST',{...body(),hora:'10:30'})).status,409);
  assert.equal((await request('/studiofy/public/studio-bella/agendamentos','POST',{...body(),profissional_id:b.panel.profissionais[0].id})).status,409);
  const times=(await request('/studiofy/public/studio-bella/horarios?'+new URLSearchParams({data:future,servico_id:service,profissional_id:professional}))).body;
  assert.ok(!times.includes('09:30'));assert.ok(!times.includes('10:30'));assert.ok(times.includes('11:00'));
  const r=await request('/studiofy/profissionais','POST',{nome:'Fernanda',ativo:true,servicos:[service]},a.token);assert.equal(r.status,200);
  assert.equal((await request('/studiofy/agendamentos','POST',{...body(),profissional_id:r.body.id},a.token)).status,201);
  await assert.rejects(db.transaction(c=>c.runAsync("INSERT INTO agendamentos (assinatura_id,nome_cliente,data,hora,status,profissional_id,duracao) VALUES ($1,'Teste',$2,'10:15','confirmado',$3,30)",[a.id,future,professional])),e=>e.code==='23505');
  const raw=await Promise.allSettled(['08:00','08:30'].map(hora=>db.runAsync("INSERT INTO agendamentos (assinatura_id,nome_cliente,data,hora,status,profissional_id,duracao) VALUES ($1,'Concorrencia SQL',$2,$3,'confirmado',$4,60)",[a.id,future,hora,professional])));
  assert.equal(raw.filter(r=>r.status==='fulfilled').length,1,'Banco impede sobreposição também fora do serviço de reservas');
  assert.equal(raw.find(r=>r.status==='rejected').reason.code,'23505');
 });
 await t.test('cancelar e remarcar atualizam agenda e previsão de 20 minutos',async()=>{
  let r=await db.getAsync('SELECT * FROM appointment_reminders WHERE appointment_id=$1',[booking]);
  assert.equal(new Date(r.due_at).toISOString(),new Date(`${future}T09:40:00-03:00`).toISOString());
  assert.equal((await request('/studiofy/agendamentos/'+booking,'PATCH',{status:'cancelado'},b.token)).status,404);
  assert.equal((await request('/studiofy/agendamentos/'+booking,'PATCH',{status:'cancelado'},a.token)).status,200);
  assert.equal((await db.getAsync('SELECT status FROM appointment_reminders WHERE appointment_id=$1',[booking])).status,'cancelled');
  assert.ok((await createStudio(db).times(a.id,future,service,professional)).includes('10:00'));
  assert.equal((await request('/studiofy/agendamentos/'+booking,'PUT',{...body(),hora:'14:00'},a.token)).status,200);
  r=await db.getAsync('SELECT * FROM appointment_reminders WHERE appointment_id=$1',[booking]);assert.equal(r.status,'pending');assert.equal(new Date(r.due_at).toISOString(),new Date(`${future}T13:40:00-03:00`).toISOString());
  assert.equal((await request('/studiofy/agendamentos/'+booking,'PUT',{...body(),hora:'16:00'},b.token)).status,404);
 });
 await t.test('bloqueios por profissional, dia inteiro, desativação e histórico',async()=>{
  assert.equal((await request('/studiofy/bloqueios','POST',{data:future,hora:'15:00',fim:'16:00',profissional_id:professional},a.token)).status,201);
  assert.equal((await request('/studiofy/agendamentos','POST',{...body(),hora:'15:00'},a.token)).status,409);
  assert.equal((await request('/studiofy/servicos/'+service,'DELETE',null,a.token)).status,200);
  assert.ok(!(await request('/studiofy/public/studio-bella')).body.servicos.some(s=>s.id===service));
  assert.ok(await db.getAsync('SELECT * FROM agendamentos WHERE id=$1',[booking]));
  assert.equal((await request('/studiofy/servicos/'+service,'PUT',{nome:'Alongamento',preco:95,duracao:60,ativo:true},a.token)).status,200);
  const day=new Date(Date.parse(future)+86400000).toISOString().slice(0,10);
  assert.equal((await request('/studiofy/bloqueios','POST',{data:day},a.token)).status,201);
  assert.deepEqual(await createStudio(db).times(a.id,day,service,professional),[]);
  await assert.rejects(db.runAsync('INSERT INTO profissional_servicos VALUES ($1,$2,$3)',[b.id,b.panel.profissionais[0].id,service]),e=>e.code==='23503');
 });
 await t.test('worker: reinício, duas instâncias, cancelamento, envio incerto e expiração',async()=>{
  const {createReminderWorker}=require('../services/reminders');
  const sent=[];const send=async(...args)=>sent.push(args);
  const clock=()=>new Date(`${future}T13:40:00-03:00`);
  await db.runAsync("UPDATE appointment_reminders SET status='cancelled' WHERE appointment_id<>$1",[booking]);
  await createReminderWorker(db,send,()=>new Date(clock().getTime()-1)).drain();assert.equal(sent.length,0);
  await Promise.all([createReminderWorker(db,send,clock).drain(),createReminderWorker(db,send,clock).drain()]);assert.equal(sent.length,1);assert.match(sent[0][2],/Gabriel/);assert.match(sent[0][2],/Alongamento/);assert.match(sent[0][2],/20 minutos/);assert.match(sent[0][2],/Studio Bella/);
  await createReminderWorker(db,send,clock).drain();assert.equal(sent.length,1);
  await request('/studiofy/agendamentos/'+booking,'PUT',{...body(),hora:'16:00'},a.token);
  let r=await db.getAsync('SELECT * FROM appointment_reminders WHERE appointment_id=$1',[booking]);assert.equal(r.status,'pending');assert.equal(r.sent_at,null);
  await request('/studiofy/agendamentos/'+booking,'PATCH',{status:'cancelado'},a.token);
  await createReminderWorker(db,send,()=>new Date(`${future}T15:40:00-03:00`)).drain();assert.equal(sent.length,1);
  await request('/studiofy/agendamentos/'+booking,'PUT',{...body(),hora:'16:00'},a.token);
  let attempts=0;const fail=async()=>{attempts++;throw Error('ambiguous');};
  await createReminderWorker(db,fail,()=>new Date(`${future}T15:40:00-03:00`)).drain();await createReminderWorker(db,fail,()=>new Date(`${future}T15:41:00-03:00`)).drain();assert.equal(attempts,1);
  assert.equal((await db.getAsync('SELECT status FROM appointment_reminders WHERE appointment_id=$1',[booking])).status,'uncertain');
  await request('/studiofy/agendamentos/'+booking,'PUT',{...body(),hora:'17:00'},a.token);
  await createReminderWorker(db,send,()=>new Date(`${future}T17:01:00-03:00`)).drain();assert.equal(sent.length,1);
  assert.equal((await db.getAsync('SELECT status FROM appointment_reminders WHERE appointment_id=$1',[booking])).status,'expired');
 });
 await t.test('admin mantém exclusão autorizada com as novas relações; outra conta permanece intacta',async()=>{
  const login=await request('/admin/login','POST',{email:'studiofy-admin@example.test',senha:'test-password'});assert.equal(login.status,200);
  const adminRequest=async(path,method='GET',body)=>fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method,headers:{'Content-Type':'application/json','x-admin-token':login.body.token},body:body?JSON.stringify(body):undefined});
  const list=await (await adminRequest('/admin/assinaturas?incluirPendentes=1')).json();const confirmationToken=[...list.assinaturas,...list.pendentes].find(row=>row.id===a.id).deleteConfirmationToken;
  assert.equal((await adminRequest('/admin/assinaturas/'+a.id,'DELETE',{confirmationToken})).status,200);
  for(const table of ['profissionais','profissional_servicos','appointment_reminders','agendamentos','servicos_assinatura','bloqueios'])assert.equal((await db.getAsync(`SELECT count(*) AS n FROM ${table} WHERE assinatura_id=$1`,[a.id])).n,0,table);
  assert.ok(await db.getAsync('SELECT id FROM assinaturas WHERE id=$1',[b.id]));assert.equal((await request('/studiofy/painel','GET',null,a.token)).status,401);
 });
});
