const {test}=require('node:test');
const assert=require('node:assert/strict');
const express=require('express');
const fs=require('node:fs');
const path=require('node:path');
const puppeteer=require('puppeteer');
const executablePath=[process.env.CHROME_PATH,puppeteer.executablePath(),'C:/Program Files/Google/Chrome/Application/chrome.exe'].find(p=>p && fs.existsSync(p));
test('Studiofy no navegador: serviço, personalização, reserva móvel e painel desktop',{skip:!executablePath,timeout:60000},async t=>{
 const env=require('./helpers/postgres').testEnvironment();
 process.env.MERCADO_PAGO_ACCESS_TOKEN='';process.env.EVOLUTION_API_URL='';process.env.EVOLUTION_API_KEY='';
 const db=require('../database');await db.ready;
 const app=express();app.use(express.json({limit:'6mb'}));app.use('/api',require('../routes'));app.use(express.static(path.resolve(__dirname,'../public')));app.get('/agendar/:slug',(req,res)=>res.sendFile(path.resolve(__dirname,'../public/agendar.html')));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await puppeteer.launch({executablePath,headless:true,args:['--no-sandbox']});
 t.after(async()=>{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();await env.cleanup();});
 const signup=await fetch(base+'/api/publico/assinaturas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({barbeariaNome:'Studio Bella',responsavelNome:'Ana Clara',telefone:'11999991111',email:'browser@example.test',senha:'test-password',metodoPagamento:'mercado_pago',diaVencimento:5,servicos:[{nome:'Manicure',preco:30}]})}).then(r=>r.json());
 assert.ok(signup.assinatura?.id);
 await db.runAsync("UPDATE assinaturas SET status='ativo',status_assinatura='ATIVA',bloqueado=0,proximo_vencimento='2099-12-01',data_vencimento='2099-12-01',weekly_hours=$1 WHERE id=$2",[JSON.stringify(Array.from({length:7},()=>[['08:00','18:00']])),signup.assinatura.id]);
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewport({width:1440,height:1000});await page.goto(base);
 await page.type('#loginIdentificadorInput','browser@example.test');await page.type('#loginSenhaInput','test-password');await Promise.all([page.waitForNavigation(),page.click('[type=submit]')]);await page.waitForSelector('[data-section="Meus serviços"]');
 await page.click('[data-section="Meus serviços"]');await page.click('#addService');await page.type('[name=nome]','Design de sobrancelhas');await page.type('[name=preco]','35');await page.$eval('[name=duracao]',el=>el.value='40');await page.click('#editor [type=submit]');await page.waitForSelector('[data-edit-service]');await page.waitForFunction(()=>document.querySelector('#view').textContent.includes('Design de sobrancelhas'));
 await page.click('[data-section="Minha página"]');await page.$eval('[name=slug]',el=>el.value='studio-bella');await page.type('[name=descricao]','Um momento de cuidado, pensado para você.');await page.click('#previewButton');await page.waitForSelector('#preview:not([hidden])');assert.match(await page.$eval('#preview',el=>el.textContent),/Studio Bella/);await page.click('#editor [type=submit]');await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('salvas'));
 const coverInput=await page.$('[name=capa]');
 await coverInput.uploadFile(path.resolve(__dirname,'../public/assets/studiofy-interior.jpg'));
 await page.waitForFunction(()=>document.querySelector('#preview .cover').style.backgroundImage.includes('data:image/jpeg'),{timeout:3000});
 await page.click('#editor [type=submit]');await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('salvas'));
 await page.reload();await page.waitForSelector('[data-section="Minha página"]');await page.click('[data-section="Minha página"]');
 await page.waitForFunction(()=>document.querySelector('#preview .cover')?.style.backgroundImage.includes('data:image/webp'),{timeout:5000});
 const savedCover=await fetch(base+'/api/studiofy/public/studio-bella').then(r=>r.json());assert.match(savedCover.capa,/^data:image\/webp/);
 const publicPreview=await browser.newPage();await publicPreview.goto(base+'/agendar/studio-bella');await publicPreview.waitForSelector('#cover');
 assert.ok((await publicPreview.$eval('#cover',el=>el.style.backgroundImage)).includes(savedCover.capa));
 await page.bringToFront();await page.click('[name=removeCover]');await page.waitForFunction(()=>!document.querySelector('#preview .cover').style.backgroundImage);
 assert.match(await page.$eval('#preview .cover',el=>getComputedStyle(el).backgroundImage),/studiofy-interior/);
 await (await page.$('[name=capa]')).uploadFile(path.resolve(__dirname,'../public/assets/studiofy-salon.jpg'));
 await page.waitForFunction(()=>!document.querySelector('[name=removeCover]').checked && document.querySelector('#preview .cover').style.backgroundImage.includes('data:image/jpeg'));
 await page.click('[name=removeCover]');await page.click('#editor [type=submit]');await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('salvas'));
 assert.equal((await fetch(base+'/api/studiofy/public/studio-bella').then(r=>r.json())).capa,null);
 await publicPreview.reload();await publicPreview.waitForSelector('#cover');assert.match(await publicPreview.$eval('#cover',el=>getComputedStyle(el).backgroundImage),/studiofy-interior/);await publicPreview.close();
 await page.click('[data-section="Dashboard"]');
 const artifacts=path.resolve(__dirname,'../../.tmp/studiofy-preview');fs.mkdirSync(artifacts,{recursive:true});await page.screenshot({path:path.join(artifacts,'dashboard-desktop.png'),fullPage:true});
 const mobile=await browser.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await mobile.goto(base+'/agendar/studio-bella');await mobile.waitForSelector('[data-service]');await mobile.screenshot({path:path.join(artifacts,'agendamento-mobile.png'),fullPage:true});
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.click('[data-service]');const date=new Date(Date.now()+86400000*2).toISOString().slice(0,10);await mobile.$eval('#date',(el,date)=>{el.value=date;el.dispatchEvent(new Event('change',{bubbles:true}));},date);await mobile.waitForSelector('[data-time]');await mobile.click('[data-time]');await mobile.type('#name','Gabriel');await mobile.type('#phone','11999992222');await mobile.click('#review');await mobile.waitForSelector('#confirm');await mobile.click('#confirm');await mobile.waitForFunction(()=>document.querySelector('#booking').textContent.includes('Agendamento confirmado!'));
 await mobile.screenshot({path:path.join(artifacts,'confirmacao-mobile.png'),fullPage:true});
 await page.bringToFront();await page.reload();await page.waitForFunction(()=>document.querySelector('#view').textContent.includes('Gabriel'));assert.equal((await db.getAsync('SELECT count(*) AS n FROM appointment_reminders')).n,1);
 await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.reload();await page.waitForSelector('[data-section="Agendamentos"]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(artifacts,'painel-mobile.png'),fullPage:true});
 await page.click('[data-section="Agendamentos"]');await page.waitForSelector('.week-calendar');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Calendário móvel deve rolar dentro do painel');
 await page.click('#nextWeek');await page.waitForSelector('.week-calendar');await page.click('#agendaToday');
 await page.click('#agendaMode');await page.waitForSelector('[data-reschedule]');
 assert.match(await page.$eval('#view',el=>el.textContent),/Gabriel/);
 await page.click('#agendaMode');
 for(let i=0;i<2 && !await page.$('[data-calendar-booking]');i++)await page.click('#nextWeek');
 await page.waitForSelector('[data-calendar-booking]');await page.click('[data-calendar-booking]');
 await page.waitForSelector('#editor');assert.equal(await page.$eval('[name=nome_cliente]',el=>el.value),'Gabriel');
 assert.deepEqual(errors,[]);
});
