const {test}=require('node:test');
const assert=require('node:assert/strict');
const express=require('express');
const fs=require('node:fs');
const path=require('node:path');
const puppeteer=require('puppeteer');
const executablePath=[process.env.CHROME_PATH,puppeteer.executablePath(),'C:/Program Files/Google/Chrome/Application/chrome.exe'].find(p=>p&&fs.existsSync(p));

test('painel: trial, expiracao sem logout, planos e checkout existente',{skip:!executablePath,timeout:60000},async t=>{
 const app=express();let status='trial_active',checkoutCalls=0,operationalCalls=0;
 app.use(express.json());
 app.get('/api/barbeiro/me',(_req,res)=>res.json({id:17,barbearia_nome:'Studio teste',acesso:{status,liberado:status!=='trial_expired',mensagem:status==='trial_expired'?'Seu teste grátis terminou. Seus dados continuam salvos.':'Teste grátis ativo.',trial:{endsAt:'2026-10-01T12:00:00Z',daysRemaining:4}}}));
 app.get('/api/studiofy/painel',(_req,res)=>{operationalCalls++;res.json({pagina:{nome:'Studio teste',slug:'studio-17'},agendamentos:[],servicos:[],profissionais:[],bloqueios:[],lembretes:[]});});
 app.get('/api/publico/assinatura-config',(_req,res)=>res.json({plan:{amountCents:6500,durationDays:30}}));
 app.post('/api/publico/assinaturas/17/checkout',(req,res)=>{assert.equal(req.headers['x-barbeiro-token'],'trial-session');checkoutCalls++;res.json({checkoutUrl:'https://sandbox.mercadopago.com.br/trial'});});
 app.use(express.static(path.resolve(__dirname,'../public')));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const browser=await puppeteer.launch({executablePath,headless:true,args:['--no-sandbox']});
 t.after(async()=>{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.evaluateOnNewDocument(()=>localStorage.setItem('barbearia_auth_token','trial-session'));
 const base=`http://127.0.0.1:${server.address().port}`;
 await page.goto(base+'/studiofy.html');await page.waitForSelector('[data-section="Dashboard"]');
 assert.match(await page.$eval('#trialBanner',e=>e.textContent),/4 dia\(s\) restantes/);
 status='trial_expired';const before=operationalCalls;
 await page.reload();await page.waitForSelector('#subscribe');
 assert.match(await page.$eval('#trialBanner',e=>e.textContent),/Seu teste grátis terminou. Seus dados continuam salvos\./);
 assert.equal(operationalCalls,before);
 assert.equal(await page.evaluate(()=>localStorage.getItem('barbearia_auth_token')),'trial-session');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/publico/assinatura-config')),page.click('#plans')]);
 await page.waitForNetworkIdle({idleTime:100});await page.waitForSelector('#subscribe');
 assert.match(await page.$eval('#view',e=>e.textContent),/65,00/);
 await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith('https://sandbox.mercadopago.com.br/')?r.respond({status:200,contentType:'text/html',body:'Pagamento'}):r.continue());
 await Promise.all([page.waitForNavigation(),page.click('#subscribe')]);
 assert.equal(checkoutCalls,1);assert.match(page.url(),/sandbox.mercadopago.com.br/);
 status='subscription_active';await page.goto(base+'/studiofy.html');await page.waitForSelector('[data-section="Dashboard"]');
 assert.equal(await page.$eval('#trialBanner',e=>e.hidden),true);
 assert.deepEqual(errors,[]);
});
