-- Schema do backend atual. Campos de data em texto preservam o contrato do painel.
-- Nao remove tabelas nem dados; nomes historicos sao mantidos apenas para importacao.

CREATE TABLE IF NOT EXISTS "configuracoes" (
  "chave" TEXT PRIMARY KEY,
  "valor" TEXT NOT NULL
);
ALTER TABLE "configuracoes" ADD COLUMN IF NOT EXISTS "chave" TEXT;
ALTER TABLE "configuracoes" ADD COLUMN IF NOT EXISTS "valor" TEXT NOT NULL;

CREATE TABLE IF NOT EXISTS "clientes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "telefone" TEXT
);
ALTER TABLE "clientes" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "clientes" ADD COLUMN IF NOT EXISTS "nome" TEXT NOT NULL;
ALTER TABLE "clientes" ADD COLUMN IF NOT EXISTS "telefone" TEXT;

CREATE TABLE IF NOT EXISTS "servicos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "preco" DOUBLE PRECISION NOT NULL
);
ALTER TABLE "servicos" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "servicos" ADD COLUMN IF NOT EXISTS "nome" TEXT NOT NULL;
ALTER TABLE "servicos" ADD COLUMN IF NOT EXISTS "preco" DOUBLE PRECISION NOT NULL;

CREATE TABLE IF NOT EXISTS "assinaturas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barbearia_nome" TEXT NOT NULL,
  "responsavel_nome" TEXT NOT NULL,
  "telefone" TEXT NOT NULL,
  "email" TEXT,
  "metodo_pagamento" TEXT NOT NULL,
  "dia_vencimento" BIGINT NOT NULL,
  "valor_mensal" DOUBLE PRECISION NOT NULL DEFAULT 60,
  "status" TEXT NOT NULL DEFAULT 'pendente',
  "suporte_numero" TEXT NOT NULL,
  "ultimo_pagamento" TEXT,
  "proximo_vencimento" TEXT,
  "observacoes" TEXT,
  "whatsapp_numero" TEXT,
  "whatsapp_status" TEXT NOT NULL DEFAULT 'nao_configurado',
  "whatsapp_session" TEXT,
  "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  "trial_usado" BIGINT NOT NULL DEFAULT 0,
  "horario_abertura" TEXT NOT NULL DEFAULT '08:00',
  "horario_almoco_inicio" TEXT NOT NULL DEFAULT '12:00',
  "horario_almoco_fim" TEXT NOT NULL DEFAULT '13:00',
  "horario_fechamento" TEXT NOT NULL DEFAULT '18:00',
  "localizacao_cidade" TEXT,
  "localizacao_rua" TEXT,
  "localizacao_referencia" TEXT,
  "senha_hash" TEXT,
  "senha_salt" TEXT,
  "whatsapp_bridge_token" TEXT,
  "whatsapp_ultimo_erro" TEXT,
  "whatsapp_ultimo_check_em" TEXT,
  "whatsapp_ultimo_qr_em" TEXT,
  "gateway_provider" TEXT,
  "gateway_status" TEXT,
  "gateway_external_reference" TEXT,
  "gateway_checkout_url" TEXT,
  "mercado_preapproval_id" TEXT,
  "mercado_payer_email" TEXT,
  "mercado_next_payment_date" TEXT,
  "mercado_last_payload" TEXT,
  "plano" TEXT NOT NULL DEFAULT 'Plano Profissional',
  "valor_plano" DOUBLE PRECISION NOT NULL DEFAULT 65,
  "status_assinatura" TEXT NOT NULL DEFAULT 'PENDENTE',
  "subscription_id" TEXT,
  "customer_id" TEXT,
  "payment_id" TEXT,
  "dias_atraso" BIGINT NOT NULL DEFAULT 0,
  "bloqueado" BIGINT NOT NULL DEFAULT 0,
  "data_bloqueio" TEXT,
  "trial" BIGINT NOT NULL DEFAULT 0,
  "data_vencimento" TEXT,
  "notification_history" TEXT,
  "dias_funcionamento" TEXT NOT NULL DEFAULT '1,2,3,4,5,6',
  "trial_started_at" TEXT,
  "trial_expires_at" TEXT
);
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "barbearia_nome" TEXT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "responsavel_nome" TEXT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "telefone" TEXT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "metodo_pagamento" TEXT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "dia_vencimento" BIGINT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "valor_mensal" DOUBLE PRECISION NOT NULL DEFAULT 60;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pendente';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "suporte_numero" TEXT NOT NULL;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "ultimo_pagamento" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "proximo_vencimento" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "observacoes" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_numero" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_status" TEXT NOT NULL DEFAULT 'nao_configurado';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_session" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "trial_usado" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "horario_abertura" TEXT NOT NULL DEFAULT '08:00';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "horario_almoco_inicio" TEXT NOT NULL DEFAULT '12:00';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "horario_almoco_fim" TEXT NOT NULL DEFAULT '13:00';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "horario_fechamento" TEXT NOT NULL DEFAULT '18:00';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "localizacao_cidade" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "localizacao_rua" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "localizacao_referencia" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "senha_hash" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "senha_salt" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_bridge_token" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_ultimo_erro" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_ultimo_check_em" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "whatsapp_ultimo_qr_em" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "gateway_provider" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "gateway_status" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "gateway_external_reference" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "gateway_checkout_url" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "mercado_preapproval_id" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "mercado_payer_email" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "mercado_next_payment_date" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "mercado_last_payload" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "plano" TEXT NOT NULL DEFAULT 'Plano Profissional';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "valor_plano" DOUBLE PRECISION NOT NULL DEFAULT 65;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "status_assinatura" TEXT NOT NULL DEFAULT 'PENDENTE';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "subscription_id" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "customer_id" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "payment_id" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "dias_atraso" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "bloqueado" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "data_bloqueio" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "trial" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "data_vencimento" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "notification_history" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "dias_funcionamento" TEXT NOT NULL DEFAULT '1,2,3,4,5,6';
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "trial_started_at" TEXT;
ALTER TABLE "assinaturas" ADD COLUMN IF NOT EXISTS "trial_expires_at" TEXT;

CREATE TABLE IF NOT EXISTS "clientes_saas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "cpf" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "telefone" TEXT NOT NULL,
  "asaas_customer_id" TEXT NOT NULL,
  "asaas_subscription_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'ativo',
  "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  UNIQUE (asaas_customer_id),
  UNIQUE (asaas_subscription_id)
);
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "nome" TEXT NOT NULL;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "cpf" TEXT NOT NULL;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "telefone" TEXT NOT NULL;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "asaas_customer_id" TEXT NOT NULL;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "asaas_subscription_id" TEXT;
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ativo';
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);
ALTER TABLE "clientes_saas" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);

CREATE TABLE IF NOT EXISTS "agendamentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT,
  "cliente_id" BIGINT,
  "servico_id" BIGINT,
  "nome_cliente" TEXT,
  "telefone" TEXT,
  "servico_nome" TEXT,
  "preco" DOUBLE PRECISION,
  "data" TEXT,
  "hora" TEXT,
  "status" TEXT,
  "lembrete_15_enviado_em" TEXT,
  "lembrete_7_enviado_em" TEXT,
  FOREIGN KEY ("servico_id") REFERENCES "servicos" ("id") ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id") ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY ("assinatura_id") REFERENCES "assinaturas" ("id") ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "cliente_id" BIGINT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "servico_id" BIGINT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "nome_cliente" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "telefone" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "servico_nome" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "preco" DOUBLE PRECISION;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "data" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "hora" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "lembrete_15_enviado_em" TEXT;
ALTER TABLE "agendamentos" ADD COLUMN IF NOT EXISTS "lembrete_7_enviado_em" TEXT;

CREATE TABLE IF NOT EXISTS "bloqueios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT,
  "data" TEXT,
  "hora" TEXT,
  FOREIGN KEY ("assinatura_id") REFERENCES "assinaturas" ("id") ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE "bloqueios" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "bloqueios" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT;
ALTER TABLE "bloqueios" ADD COLUMN IF NOT EXISTS "data" TEXT;
ALTER TABLE "bloqueios" ADD COLUMN IF NOT EXISTS "hora" TEXT;

CREATE TABLE IF NOT EXISTS "sessoes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT NOT NULL,
  "telefone" TEXT NOT NULL,
  "etapa" TEXT NOT NULL,
  "servico" TEXT,
  "preco" DOUBLE PRECISION,
  "nome" TEXT,
  "data" TEXT,
  "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  "data_json" TEXT,
  UNIQUE (assinatura_id, telefone),
  FOREIGN KEY ("assinatura_id") REFERENCES "assinaturas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "telefone" TEXT NOT NULL;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "etapa" TEXT NOT NULL;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "servico" TEXT;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "preco" DOUBLE PRECISION;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "nome" TEXT;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "data" TEXT;
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);
ALTER TABLE "sessoes" ADD COLUMN IF NOT EXISTS "data_json" TEXT;

CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT NOT NULL,
  "token_hash" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "used_at" TEXT,
  "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  FOREIGN KEY ("assinatura_id") REFERENCES "assinaturas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "token_hash" TEXT NOT NULL;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "expires_at" TEXT NOT NULL;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "used_at" TEXT;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);

CREATE TABLE IF NOT EXISTS "servicos_assinatura" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT NOT NULL,
  "nome" TEXT NOT NULL,
  "preco" DOUBLE PRECISION NOT NULL,
  "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text),
  FOREIGN KEY ("assinatura_id") REFERENCES "assinaturas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE "servicos_assinatura" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "servicos_assinatura" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "servicos_assinatura" ADD COLUMN IF NOT EXISTS "nome" TEXT NOT NULL;
ALTER TABLE "servicos_assinatura" ADD COLUMN IF NOT EXISTS "preco" DOUBLE PRECISION NOT NULL;
ALTER TABLE "servicos_assinatura" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT (CURRENT_TIMESTAMP::text);

CREATE TABLE IF NOT EXISTS "mercado_pago_orders" (
  "reference" TEXT PRIMARY KEY,
  "assinatura_id" BIGINT NOT NULL,
  "amount_cents" BIGINT NOT NULL,
  "live_mode" BIGINT NOT NULL,
  "preference_id" TEXT,
  "checkout_url" TEXT,
  "expires_at" TEXT NOT NULL,
  "credited_payment_id" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  UNIQUE (credited_payment_id)
);
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "reference" TEXT;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "amount_cents" BIGINT NOT NULL;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "live_mode" BIGINT NOT NULL;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "preference_id" TEXT;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "checkout_url" TEXT;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "expires_at" TEXT NOT NULL;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "credited_payment_id" TEXT;
ALTER TABLE "mercado_pago_orders" ADD COLUMN IF NOT EXISTS "created_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text);

CREATE TABLE IF NOT EXISTS "mercado_pago_payments" (
  "payment_id" TEXT PRIMARY KEY,
  "order_reference" TEXT NOT NULL,
  "assinatura_id" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "amount_cents" BIGINT NOT NULL,
  "credited_at" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "payment_id" TEXT;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "order_reference" TEXT NOT NULL;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "amount_cents" BIGINT NOT NULL;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "credited_at" TEXT;
ALTER TABLE "mercado_pago_payments" ADD COLUMN IF NOT EXISTS "updated_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text);

CREATE TABLE IF NOT EXISTS "whatsapp_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assinatura_id" BIGINT NOT NULL,
  "instance" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "response" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "lease_until" BIGINT NOT NULL DEFAULT 0,
  "attempts" BIGINT NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  "sent_at" TEXT,
  UNIQUE (instance, message_id)
);
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "assinatura_id" BIGINT NOT NULL;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "instance" TEXT NOT NULL;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "message_id" TEXT NOT NULL;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "response" TEXT NOT NULL;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "lease_until" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "attempts" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "created_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text);
ALTER TABLE "whatsapp_messages" ADD COLUMN IF NOT EXISTS "sent_at" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_tokens_uniq
          ON password_reset_tokens (assinatura_id)
          WHERE used_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_agendamentos_tenant_horario
      ON agendamentos (COALESCE(assinatura_id, 0), data, hora) WHERE status = 'confirmado';
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_pending ON whatsapp_messages(status, lease_until, id);
CREATE TABLE IF NOT EXISTS sqlite_imports (source_hash TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, counts JSONB NOT NULL);

CREATE INDEX IF NOT EXISTS idx_clientes_telefone ON clientes(telefone);
