ALTER TABLE assinaturas ADD COLUMN public_slug TEXT UNIQUE;
ALTER TABLE assinaturas ADD COLUMN page_description TEXT NOT NULL DEFAULT '';
ALTER TABLE assinaturas ADD COLUMN cover_image TEXT;
ALTER TABLE assinaturas ADD COLUMN logo_image TEXT;
ALTER TABLE assinaturas ADD COLUMN page_color TEXT NOT NULL DEFAULT '#2878ff';
ALTER TABLE assinaturas ADD COLUMN weekly_hours JSONB;
UPDATE assinaturas SET public_slug = 'studio-' || id;
ALTER TABLE servicos_assinatura ADD COLUMN descricao TEXT NOT NULL DEFAULT '';
ALTER TABLE servicos_assinatura ADD COLUMN duracao INTEGER NOT NULL DEFAULT 30 CHECK (duracao BETWEEN 5 AND 720);
ALTER TABLE servicos_assinatura ADD COLUMN foto TEXT;
ALTER TABLE servicos_assinatura ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE servicos_assinatura ADD CONSTRAINT studio_service_owner UNIQUE (assinatura_id,id);
CREATE TABLE profissionais (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 assinatura_id BIGINT NOT NULL REFERENCES assinaturas(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 nome TEXT NOT NULL, ativo BOOLEAN NOT NULL DEFAULT true,
 UNIQUE (assinatura_id, id)
);
INSERT INTO profissionais (assinatura_id, nome) SELECT id, responsavel_nome FROM assinaturas;
CREATE TABLE profissional_servicos (
 assinatura_id BIGINT NOT NULL REFERENCES assinaturas(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 profissional_id BIGINT NOT NULL REFERENCES profissionais(id) ON DELETE CASCADE,
 servico_id BIGINT NOT NULL REFERENCES servicos_assinatura(id) ON DELETE CASCADE,
 PRIMARY KEY (profissional_id, servico_id),
 FOREIGN KEY (assinatura_id,profissional_id) REFERENCES profissionais(assinatura_id,id) ON DELETE CASCADE,
 FOREIGN KEY (assinatura_id,servico_id) REFERENCES servicos_assinatura(assinatura_id,id) ON DELETE CASCADE
);
INSERT INTO profissional_servicos SELECT s.assinatura_id, p.id, s.id FROM servicos_assinatura s JOIN profissionais p USING (assinatura_id);
ALTER TABLE agendamentos ADD COLUMN profissional_id BIGINT REFERENCES profissionais(id);
ALTER TABLE agendamentos ADD COLUMN duracao INTEGER NOT NULL DEFAULT 30 CHECK (duracao BETWEEN 5 AND 720);
ALTER TABLE agendamentos ADD COLUMN studio_service_id BIGINT REFERENCES servicos_assinatura(id) ON DELETE SET NULL;
UPDATE agendamentos a SET profissional_id = p.id FROM profissionais p WHERE a.assinatura_id = p.assinatura_id;
ALTER TABLE bloqueios ADD COLUMN profissional_id BIGINT REFERENCES profissionais(id);
ALTER TABLE bloqueios ADD COLUMN fim TEXT;
CREATE TABLE appointment_reminders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 appointment_id BIGINT NOT NULL UNIQUE REFERENCES agendamentos(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 assinatura_id BIGINT NOT NULL REFERENCES assinaturas(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 due_at TIMESTAMPTZ NOT NULL, sent_at TIMESTAMPTZ,
 status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','cancelled','uncertain','expired')),
 attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT, claimed_at TIMESTAMPTZ
);
CREATE INDEX reminder_due ON appointment_reminders (due_at) WHERE status = 'pending';
-- Existing exact-start protection is retained per professional. Interval checks below also cover legacy writers.
DROP INDEX IF EXISTS idx_agendamentos_tenant_horario;
CREATE UNIQUE INDEX idx_agendamentos_tenant_horario ON agendamentos (COALESCE(assinatura_id,0),COALESCE(profissional_id,0),data,hora) WHERE status = 'confirmado';
CREATE FUNCTION studiofy_booking_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(hashtext(current_schema()), 1);
 IF NEW.profissional_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM profissionais WHERE id=NEW.profissional_id AND assinatura_id=NEW.assinatura_id) THEN
  RAISE EXCEPTION 'Professional outside tenant' USING ERRCODE='23514';
 END IF;
 IF NEW.studio_service_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM servicos_assinatura WHERE id=NEW.studio_service_id AND assinatura_id=NEW.assinatura_id) THEN
  RAISE EXCEPTION 'Service outside tenant' USING ERRCODE='23514';
 END IF;
 IF NEW.status='confirmado' AND EXISTS (
  SELECT 1 FROM agendamentos a WHERE a.assinatura_id=NEW.assinatura_id AND a.data=NEW.data
  AND a.id<>NEW.id AND a.status='confirmado'
  AND (a.profissional_id=NEW.profissional_id OR a.profissional_id IS NULL OR NEW.profissional_id IS NULL)
  AND a.hora::time < NEW.hora::time + make_interval(mins=>NEW.duracao)
  AND NEW.hora::time < a.hora::time + make_interval(mins=>a.duracao)
 ) THEN RAISE EXCEPTION 'Appointment conflict' USING ERRCODE='23505'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER studiofy_booking_guard BEFORE INSERT OR UPDATE ON agendamentos FOR EACH ROW EXECUTE FUNCTION studiofy_booking_guard();
CREATE FUNCTION studiofy_reminder_sync() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status='confirmado' THEN
  INSERT INTO appointment_reminders (appointment_id,assinatura_id,due_at)
   VALUES (NEW.id,NEW.assinatura_id,(NEW.data || ' ' || NEW.hora)::timestamp AT TIME ZONE 'America/Sao_Paulo' - interval '20 minutes')
  ON CONFLICT (appointment_id) DO UPDATE SET due_at=EXCLUDED.due_at,
   status=CASE WHEN appointment_reminders.due_at<>EXCLUDED.due_at OR appointment_reminders.status='cancelled' THEN 'pending' ELSE appointment_reminders.status END,
   sent_at=CASE WHEN appointment_reminders.due_at<>EXCLUDED.due_at THEN NULL ELSE appointment_reminders.sent_at END,
   attempts=CASE WHEN appointment_reminders.due_at<>EXCLUDED.due_at THEN 0 ELSE appointment_reminders.attempts END,
   last_error=CASE WHEN appointment_reminders.due_at<>EXCLUDED.due_at THEN NULL ELSE appointment_reminders.last_error END;
 ELSE UPDATE appointment_reminders SET status='cancelled' WHERE appointment_id=NEW.id AND status<>'sent'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER studiofy_reminder_sync AFTER INSERT OR UPDATE ON agendamentos FOR EACH ROW WHEN (NEW.assinatura_id IS NOT NULL) EXECUTE FUNCTION studiofy_reminder_sync();
INSERT INTO appointment_reminders (appointment_id,assinatura_id,due_at)
 SELECT id,assinatura_id,(data || ' ' || hora)::timestamp AT TIME ZONE 'America/Sao_Paulo' - interval '20 minutes'
 FROM agendamentos WHERE assinatura_id IS NOT NULL AND status='confirmado'
 AND data ~ '^\d{4}-\d{2}-\d{2}$' AND hora ~ '^\d{2}:\d{2}$'
 AND data >= to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo','YYYY-MM-DD');
